-- LIMPIEZA (Opcional: elimina si ya existen para recrear)
DROP TABLE IF EXISTS notifications CASCADE;
DROP TABLE IF EXISTS payments CASCADE;
DROP TABLE IF EXISTS profiles CASCADE;

-- TABLA DE PERFILES (Extensión de Auth.users)
CREATE TABLE profiles (
  id UUID REFERENCES auth.users ON DELETE CASCADE PRIMARY KEY,
  nombre TEXT,
  dni TEXT UNIQUE,
  telefono TEXT,
  fecha_vencimiento DATE,
  rol TEXT DEFAULT 'socio', -- 'socio' o 'admin'
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- FUNCION PARA CREAR PERFIL AUTOMATICAMENTE
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger AS $$
BEGIN
  INSERT INTO public.profiles (id, nombre, dni, fecha_vencimiento, rol)
  VALUES (
    new.id, 
    new.raw_user_meta_data->>'nombre', 
    new.raw_user_meta_data->>'dni',
    CASE 
      WHEN (new.raw_user_meta_data->>'fecha_vencimiento') IS NOT NULL AND (new.raw_user_meta_data->>'fecha_vencimiento') <> ''
      THEN (new.raw_user_meta_data->>'fecha_vencimiento')::date
      ELSE CURRENT_DATE + INTERVAL '1 month'
    END,
    COALESCE(new.raw_user_meta_data->>'rol', 'socio')
  );
  RETURN new;
EXCEPTION
  WHEN OTHERS THEN
    -- Si falla el trigger, igual retornamos 'new' para que el usuario se cree en AUTH
    -- Aunque el perfil no se cree, esto evita que el proceso de registro se bloquee
    RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- TRIGGER QUE SE DISPARA AL INSERTAR EN AUTH.USERS
CREATE OR REPLACE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();

-- TABLA DE PAGOS
CREATE TABLE payments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES profiles(id) ON DELETE CASCADE,
  monto NUMERIC NOT NULL,
  metodo_pago TEXT, -- 'efectivo', 'transferencia'
  estado TEXT DEFAULT 'pending', -- 'pending', 'approved', 'rejected'
  comprobante_url TEXT,
  fecha_pago DATE DEFAULT CURRENT_DATE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- TABLA DE NOTIFICACIONES
CREATE TABLE notifications (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tipo TEXT NOT NULL, -- 'general', 'individual'
  target_user_id UUID REFERENCES profiles(id) ON DELETE SET NULL,
  titulo TEXT NOT NULL,
  mensaje TEXT NOT NULL,
  image_url TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- RLS (Row Level Security) - Ejemplos básicos
ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public profiles are viewable by everyone" ON profiles FOR SELECT USING (true);
CREATE POLICY "Users can update own profile" ON profiles FOR UPDATE USING (auth.uid() = id);
CREATE POLICY "Users can insert own profile" ON profiles FOR INSERT WITH CHECK (auth.uid() = id);

ALTER TABLE payments ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can see own payments" ON payments FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users can insert own payments" ON payments FOR INSERT WITH CHECK (auth.uid() = user_id);

ALTER TABLE notifications ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Notifications are viewable by assigned users or all if general" ON notifications 
FOR SELECT USING (tipo = 'general' OR target_user_id = auth.uid());
